#ifndef OPENSTEAM_LIB_STEAMAPI_GLOBAL_H
#define OPENSTEAM_LIB_STEAMAPI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPENSTEAM_LIB_STEAMAPI_LIBRARY)
#  define OPENSTEAM_LIB_STEAMAPISHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPENSTEAM_LIB_STEAMAPISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPENSTEAM_LIB_STEAMAPI_GLOBAL_H
