#ifndef OPENSTEAM_LIB_COMMON_GLOBAL_H
#define OPENSTEAM_LIB_COMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPENSTEAM_LIB_COMMON_LIBRARY)
#  define OPENSTEAM_LIB_COMMONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPENSTEAM_LIB_COMMONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPENSTEAM_LIB_COMMON_GLOBAL_H
